default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: <%= ENV.fetch("PGUSER", `whoami`.strip) %>
  password: <%= ENV["PGPASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: acr_development

test:
  <<: *default
  database: acr_test
