default:
  GR1:
    # Buy-One-Get-One-Free
    bogof: true

  SR1:
    # price becomes 4.50 when qty >= 3
    bulk_price_drop:
      min_qty: 3
      new_unit_price: 4.50

  CF1:
    # price becomes 2/3 of base when qty >= 3
    # compute discount on the line, then round
    fraction_drop:
      min_qty: 3
      numerator: 2
      denominator: 3
      rounding: line_total

  _global:
    buy_any_get_gift:
      gift_code: GR1
      gift_qty: 1